import {
  Smartphone,
  Home,
  Sparkles,
  ShoppingBag,
  Shirt,
  Car,
  Wrench,
  Gamepad2,
  Baby,
  Heart,
  BookOpen,
  PawPrint,
  Briefcase,
  Dumbbell,
  Palette,
  Crown,
  TrendingUp,
} from 'lucide-react';

export const CATEGORIES = [
  { name: 'Electronics', icon: Smartphone },
  { name: 'Home & Kitchen', icon: Home },
  { name: 'Beauty', icon: Sparkles },
  { name: 'Grocery', icon: ShoppingBag },
  { name: 'Fashion', icon: Shirt },
  { name: 'Automotive', icon: Car },
  { name: 'Industrial', icon: Wrench },
  { name: 'Toys', icon: Gamepad2 },
  { name: 'Baby', icon: Baby },
  { name: 'Health', icon: Heart },
  { name: 'Books', icon: BookOpen },
  { name: 'Pet Supplies', icon: PawPrint },
  { name: 'Office', icon: Briefcase },
  { name: 'Sports', icon: Dumbbell },
  { name: 'Handmade', icon: Palette },
  { name: 'Luxury', icon: Crown },
  { name: 'Emerging', icon: TrendingUp },
];
