/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface KeywordResearchRequest {
  'searchVolumeEstimate' : [] | [bigint],
  'keywordDifficultyScore' : [] | [number],
  'longTailSuggestions' : [] | [Array<string>],
  'cpcEstimate' : [] | [number],
}
export interface OpportunityScore {
  'growthScore' : number,
  'competitionScore' : number,
  'score' : number,
  'demandScore' : number,
  'marginScore' : number,
}
export interface OpportunityScoreFilters {
  'minScore' : number,
  'category' : [] | [string],
}
export interface Product {
  'id' : ProductId,
  'bsr' : bigint,
  'mrp' : number,
  'subcategory' : string,
  'asin' : string,
  'estimatedMonthlySales' : bigint,
  'productName' : string,
  'lastModified' : Time,
  'sellerType' : SellerType,
  'availableStock' : bigint,
  'category' : string,
  'brand' : string,
  'margin' : number,
  'rating' : number,
  'price' : number,
  'reviewCount' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface ProductAddRequest {
  'bsr' : bigint,
  'mrp' : number,
  'subcategory' : string,
  'asin' : string,
  'estimatedMonthlySales' : bigint,
  'productName' : string,
  'sellerType' : SellerType,
  'availableStock' : bigint,
  'category' : string,
  'brand' : string,
  'margin' : number,
  'rating' : number,
  'price' : number,
  'reviewCount' : bigint,
  'images' : Array<ExternalBlob>,
}
export type ProductId = string;
export interface ProductSearchFilters {
  'lowFBACount' : boolean,
  'subcategory' : [] | [string],
  'nonBrandedFriendly' : boolean,
  'ratingThreshold' : [] | [number],
  'priceRange' : [] | [[number, number]],
  'monthlyRevenueRange' : [] | [[number, number]],
  'highMarginThreshold' : boolean,
  'bsrRange' : [] | [[bigint, bigint]],
  'lightweightPreference' : boolean,
  'category' : [] | [string],
  'reviewCountMax' : [] | [bigint],
  'highReviewGrowth' : boolean,
}
export type ProductSearchResult = { 'error' : string } |
  { 'success' : Array<Product> };
export interface ProductTrend {
  'risingStar' : boolean,
  'reviewGrowthSpike' : boolean,
  'priceIncreaseTrend' : boolean,
  'seasonalDemandPattern' : boolean,
}
export interface SellerAnalysisRequest {
  'averagePrice' : [] | [number],
  'averageReviews' : [] | [bigint],
  'averageRating' : [] | [number],
  'weaknessDetection' : [] | [Array<string>],
  'listingQualityScore' : [] | [number],
}
export type SellerType = { 'fba' : null } |
  { 'easyShip' : null } |
  { 'sellerFulfilled' : null };
export type SubscriptionTier = { 'pro' : null } |
  { 'premium' : null } |
  { 'free' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'subscriptionTier' : SubscriptionTier,
  'alertPreferences' : Array<string>,
  'savedProductLists' : Array<string>,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[ProductAddRequest], ProductId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'forceProductUpdate' : ActorMethod<[], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOpportunityScore' : ActorMethod<[string], OpportunityScore>,
  'getOpportunityScoreFiltered' : ActorMethod<
    [OpportunityScoreFilters],
    Array<Product>
  >,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveKeywordResearch' : ActorMethod<[KeywordResearchRequest], undefined>,
  'saveProductTrends' : ActorMethod<[string, ProductTrend], undefined>,
  'saveSellerAnalysis' : ActorMethod<[SellerAnalysisRequest], undefined>,
  'searchProducts' : ActorMethod<[ProductSearchFilters], ProductSearchResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];