/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SellerType = IDL.Variant({
  'fba' : IDL.Null,
  'easyShip' : IDL.Null,
  'sellerFulfilled' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductAddRequest = IDL.Record({
  'bsr' : IDL.Nat,
  'mrp' : IDL.Float64,
  'subcategory' : IDL.Text,
  'asin' : IDL.Text,
  'estimatedMonthlySales' : IDL.Nat,
  'productName' : IDL.Text,
  'sellerType' : SellerType,
  'availableStock' : IDL.Nat,
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'margin' : IDL.Float64,
  'rating' : IDL.Float64,
  'price' : IDL.Float64,
  'reviewCount' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const ProductId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Product = IDL.Record({
  'id' : ProductId,
  'bsr' : IDL.Nat,
  'mrp' : IDL.Float64,
  'subcategory' : IDL.Text,
  'asin' : IDL.Text,
  'estimatedMonthlySales' : IDL.Nat,
  'productName' : IDL.Text,
  'lastModified' : Time,
  'sellerType' : SellerType,
  'availableStock' : IDL.Nat,
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'margin' : IDL.Float64,
  'rating' : IDL.Float64,
  'price' : IDL.Float64,
  'reviewCount' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const SubscriptionTier = IDL.Variant({
  'pro' : IDL.Null,
  'premium' : IDL.Null,
  'free' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'subscriptionTier' : SubscriptionTier,
  'alertPreferences' : IDL.Vec(IDL.Text),
  'savedProductLists' : IDL.Vec(IDL.Text),
  'email' : IDL.Text,
});
export const OpportunityScore = IDL.Record({
  'growthScore' : IDL.Float64,
  'competitionScore' : IDL.Float64,
  'score' : IDL.Float64,
  'demandScore' : IDL.Float64,
  'marginScore' : IDL.Float64,
});
export const OpportunityScoreFilters = IDL.Record({
  'minScore' : IDL.Float64,
  'category' : IDL.Opt(IDL.Text),
});
export const KeywordResearchRequest = IDL.Record({
  'searchVolumeEstimate' : IDL.Opt(IDL.Nat),
  'keywordDifficultyScore' : IDL.Opt(IDL.Float64),
  'longTailSuggestions' : IDL.Opt(IDL.Vec(IDL.Text)),
  'cpcEstimate' : IDL.Opt(IDL.Float64),
});
export const ProductTrend = IDL.Record({
  'risingStar' : IDL.Bool,
  'reviewGrowthSpike' : IDL.Bool,
  'priceIncreaseTrend' : IDL.Bool,
  'seasonalDemandPattern' : IDL.Bool,
});
export const SellerAnalysisRequest = IDL.Record({
  'averagePrice' : IDL.Opt(IDL.Float64),
  'averageReviews' : IDL.Opt(IDL.Nat),
  'averageRating' : IDL.Opt(IDL.Float64),
  'weaknessDetection' : IDL.Opt(IDL.Vec(IDL.Text)),
  'listingQualityScore' : IDL.Opt(IDL.Float64),
});
export const ProductSearchFilters = IDL.Record({
  'lowFBACount' : IDL.Bool,
  'subcategory' : IDL.Opt(IDL.Text),
  'nonBrandedFriendly' : IDL.Bool,
  'ratingThreshold' : IDL.Opt(IDL.Float64),
  'priceRange' : IDL.Opt(IDL.Tuple(IDL.Float64, IDL.Float64)),
  'monthlyRevenueRange' : IDL.Opt(IDL.Tuple(IDL.Float64, IDL.Float64)),
  'highMarginThreshold' : IDL.Bool,
  'bsrRange' : IDL.Opt(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'lightweightPreference' : IDL.Bool,
  'category' : IDL.Opt(IDL.Text),
  'reviewCountMax' : IDL.Opt(IDL.Nat),
  'highReviewGrowth' : IDL.Bool,
});
export const ProductSearchResult = IDL.Variant({
  'error' : IDL.Text,
  'success' : IDL.Vec(Product),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([ProductAddRequest], [ProductId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'forceProductUpdate' : IDL.Func([], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOpportunityScore' : IDL.Func([IDL.Text], [OpportunityScore], ['query']),
  'getOpportunityScoreFiltered' : IDL.Func(
      [OpportunityScoreFilters],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveKeywordResearch' : IDL.Func([KeywordResearchRequest], [], []),
  'saveProductTrends' : IDL.Func([IDL.Text, ProductTrend], [], []),
  'saveSellerAnalysis' : IDL.Func([SellerAnalysisRequest], [], []),
  'searchProducts' : IDL.Func(
      [ProductSearchFilters],
      [ProductSearchResult],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SellerType = IDL.Variant({
    'fba' : IDL.Null,
    'easyShip' : IDL.Null,
    'sellerFulfilled' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductAddRequest = IDL.Record({
    'bsr' : IDL.Nat,
    'mrp' : IDL.Float64,
    'subcategory' : IDL.Text,
    'asin' : IDL.Text,
    'estimatedMonthlySales' : IDL.Nat,
    'productName' : IDL.Text,
    'sellerType' : SellerType,
    'availableStock' : IDL.Nat,
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'margin' : IDL.Float64,
    'rating' : IDL.Float64,
    'price' : IDL.Float64,
    'reviewCount' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const ProductId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Product = IDL.Record({
    'id' : ProductId,
    'bsr' : IDL.Nat,
    'mrp' : IDL.Float64,
    'subcategory' : IDL.Text,
    'asin' : IDL.Text,
    'estimatedMonthlySales' : IDL.Nat,
    'productName' : IDL.Text,
    'lastModified' : Time,
    'sellerType' : SellerType,
    'availableStock' : IDL.Nat,
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'margin' : IDL.Float64,
    'rating' : IDL.Float64,
    'price' : IDL.Float64,
    'reviewCount' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const SubscriptionTier = IDL.Variant({
    'pro' : IDL.Null,
    'premium' : IDL.Null,
    'free' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'subscriptionTier' : SubscriptionTier,
    'alertPreferences' : IDL.Vec(IDL.Text),
    'savedProductLists' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
  });
  const OpportunityScore = IDL.Record({
    'growthScore' : IDL.Float64,
    'competitionScore' : IDL.Float64,
    'score' : IDL.Float64,
    'demandScore' : IDL.Float64,
    'marginScore' : IDL.Float64,
  });
  const OpportunityScoreFilters = IDL.Record({
    'minScore' : IDL.Float64,
    'category' : IDL.Opt(IDL.Text),
  });
  const KeywordResearchRequest = IDL.Record({
    'searchVolumeEstimate' : IDL.Opt(IDL.Nat),
    'keywordDifficultyScore' : IDL.Opt(IDL.Float64),
    'longTailSuggestions' : IDL.Opt(IDL.Vec(IDL.Text)),
    'cpcEstimate' : IDL.Opt(IDL.Float64),
  });
  const ProductTrend = IDL.Record({
    'risingStar' : IDL.Bool,
    'reviewGrowthSpike' : IDL.Bool,
    'priceIncreaseTrend' : IDL.Bool,
    'seasonalDemandPattern' : IDL.Bool,
  });
  const SellerAnalysisRequest = IDL.Record({
    'averagePrice' : IDL.Opt(IDL.Float64),
    'averageReviews' : IDL.Opt(IDL.Nat),
    'averageRating' : IDL.Opt(IDL.Float64),
    'weaknessDetection' : IDL.Opt(IDL.Vec(IDL.Text)),
    'listingQualityScore' : IDL.Opt(IDL.Float64),
  });
  const ProductSearchFilters = IDL.Record({
    'lowFBACount' : IDL.Bool,
    'subcategory' : IDL.Opt(IDL.Text),
    'nonBrandedFriendly' : IDL.Bool,
    'ratingThreshold' : IDL.Opt(IDL.Float64),
    'priceRange' : IDL.Opt(IDL.Tuple(IDL.Float64, IDL.Float64)),
    'monthlyRevenueRange' : IDL.Opt(IDL.Tuple(IDL.Float64, IDL.Float64)),
    'highMarginThreshold' : IDL.Bool,
    'bsrRange' : IDL.Opt(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'lightweightPreference' : IDL.Bool,
    'category' : IDL.Opt(IDL.Text),
    'reviewCountMax' : IDL.Opt(IDL.Nat),
    'highReviewGrowth' : IDL.Bool,
  });
  const ProductSearchResult = IDL.Variant({
    'error' : IDL.Text,
    'success' : IDL.Vec(Product),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([ProductAddRequest], [ProductId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'forceProductUpdate' : IDL.Func([], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOpportunityScore' : IDL.Func([IDL.Text], [OpportunityScore], ['query']),
    'getOpportunityScoreFiltered' : IDL.Func(
        [OpportunityScoreFilters],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveKeywordResearch' : IDL.Func([KeywordResearchRequest], [], []),
    'saveProductTrends' : IDL.Func([IDL.Text, ProductTrend], [], []),
    'saveSellerAnalysis' : IDL.Func([SellerAnalysisRequest], [], []),
    'searchProducts' : IDL.Func(
        [ProductSearchFilters],
        [ProductSearchResult],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };