/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Product {
    id: ProductId;
    bsr: bigint;
    mrp: number;
    subcategory: string;
    asin: string;
    estimatedMonthlySales: bigint;
    productName: string;
    lastModified: Time;
    sellerType: SellerType;
    availableStock: bigint;
    category: string;
    brand: string;
    margin: number;
    rating: number;
    price: number;
    reviewCount: bigint;
    images: Array<ExternalBlob>;
}
export type ProductSearchResult = {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: Array<Product>;
};
export interface ProductTrend {
    risingStar: boolean;
    reviewGrowthSpike: boolean;
    priceIncreaseTrend: boolean;
    seasonalDemandPattern: boolean;
}
export type Time = bigint;
export interface ProductSearchFilters {
    lowFBACount: boolean;
    subcategory?: string;
    nonBrandedFriendly: boolean;
    ratingThreshold?: number;
    priceRange?: [number, number];
    monthlyRevenueRange?: [number, number];
    highMarginThreshold: boolean;
    bsrRange?: [bigint, bigint];
    lightweightPreference: boolean;
    category?: string;
    reviewCountMax?: bigint;
    highReviewGrowth: boolean;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface SellerAnalysisRequest {
    averagePrice?: number;
    averageReviews?: bigint;
    averageRating?: number;
    weaknessDetection?: Array<string>;
    listingQualityScore?: number;
}
export interface ProductAddRequest {
    bsr: bigint;
    mrp: number;
    subcategory: string;
    asin: string;
    estimatedMonthlySales: bigint;
    productName: string;
    sellerType: SellerType;
    availableStock: bigint;
    category: string;
    brand: string;
    margin: number;
    rating: number;
    price: number;
    reviewCount: bigint;
    images: Array<ExternalBlob>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface OpportunityScoreFilters {
    minScore: number;
    category?: string;
}
export interface OpportunityScore {
    growthScore: number;
    competitionScore: number;
    score: number;
    demandScore: number;
    marginScore: number;
}
export interface KeywordResearchRequest {
    searchVolumeEstimate?: bigint;
    keywordDifficultyScore?: number;
    longTailSuggestions?: Array<string>;
    cpcEstimate?: number;
}
export type ProductId = string;
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    subscriptionTier: SubscriptionTier;
    alertPreferences: Array<string>;
    savedProductLists: Array<string>;
    email: string;
}
export enum SellerType {
    fba = "fba",
    easyShip = "easyShip",
    sellerFulfilled = "sellerFulfilled"
}
export enum SubscriptionTier {
    pro = "pro",
    premium = "premium",
    free = "free"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProduct(productRequest: ProductAddRequest): Promise<ProductId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    forceProductUpdate(): Promise<void>;
    getAllProducts(): Promise<Array<Product>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getOpportunityScore(productId: string): Promise<OpportunityScore>;
    getOpportunityScoreFiltered(filters: OpportunityScoreFilters): Promise<Array<Product>>;
    getProduct(id: ProductId): Promise<Product>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveKeywordResearch(request: KeywordResearchRequest): Promise<void>;
    saveProductTrends(productId: string, trend: ProductTrend): Promise<void>;
    saveSellerAnalysis(request: SellerAnalysisRequest): Promise<void>;
    searchProducts(filters: ProductSearchFilters): Promise<ProductSearchResult>;
}
import type { ExternalBlob as _ExternalBlob, KeywordResearchRequest as _KeywordResearchRequest, OpportunityScoreFilters as _OpportunityScoreFilters, Product as _Product, ProductAddRequest as _ProductAddRequest, ProductId as _ProductId, ProductSearchFilters as _ProductSearchFilters, ProductSearchResult as _ProductSearchResult, SellerAnalysisRequest as _SellerAnalysisRequest, SellerType as _SellerType, SubscriptionTier as _SubscriptionTier, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProduct(arg0: ProductAddRequest): Promise<ProductId> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(await to_candid_ProductAddRequest_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(await to_candid_ProductAddRequest_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async forceProductUpdate(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.forceProductUpdate();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.forceProductUpdate();
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpportunityScore(arg0: string): Promise<OpportunityScore> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpportunityScore(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpportunityScore(arg0);
            return result;
        }
    }
    async getOpportunityScoreFiltered(arg0: OpportunityScoreFilters): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpportunityScoreFiltered(to_candid_OpportunityScoreFilters_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpportunityScoreFiltered(to_candid_OpportunityScoreFilters_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_Product_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_Product_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveKeywordResearch(arg0: KeywordResearchRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveKeywordResearch(to_candid_KeywordResearchRequest_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveKeywordResearch(to_candid_KeywordResearchRequest_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveProductTrends(arg0: string, arg1: ProductTrend): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProductTrends(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProductTrends(arg0, arg1);
            return result;
        }
    }
    async saveSellerAnalysis(arg0: SellerAnalysisRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSellerAnalysis(to_candid_SellerAnalysisRequest_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSellerAnalysis(to_candid_SellerAnalysisRequest_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchProducts(arg0: ProductSearchFilters): Promise<ProductSearchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(to_candid_ProductSearchFilters_n40(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ProductSearchResult_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(to_candid_ProductSearchFilters_n40(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ProductSearchResult_n42(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_ProductSearchResult_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductSearchResult): Promise<ProductSearchResult> {
    return await from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_SellerType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SellerType): SellerType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionTier_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionTier): SubscriptionTier {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    bsr: bigint;
    mrp: number;
    subcategory: string;
    asin: string;
    estimatedMonthlySales: bigint;
    productName: string;
    lastModified: _Time;
    sellerType: _SellerType;
    availableStock: bigint;
    category: string;
    brand: string;
    margin: number;
    rating: number;
    price: number;
    reviewCount: bigint;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: ProductId;
    bsr: bigint;
    mrp: number;
    subcategory: string;
    asin: string;
    estimatedMonthlySales: bigint;
    productName: string;
    lastModified: Time;
    sellerType: SellerType;
    availableStock: bigint;
    category: string;
    brand: string;
    margin: number;
    rating: number;
    price: number;
    reviewCount: bigint;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        bsr: value.bsr,
        mrp: value.mrp,
        subcategory: value.subcategory,
        asin: value.asin,
        estimatedMonthlySales: value.estimatedMonthlySales,
        productName: value.productName,
        lastModified: value.lastModified,
        sellerType: from_candid_SellerType_n19(_uploadFile, _downloadFile, value.sellerType),
        availableStock: value.availableStock,
        category: value.category,
        brand: value.brand,
        margin: value.margin,
        rating: value.rating,
        price: value.price,
        reviewCount: value.reviewCount,
        images: await from_candid_vec_n21(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    subscriptionTier: _SubscriptionTier;
    alertPreferences: Array<string>;
    savedProductLists: Array<string>;
    email: string;
}): {
    name: string;
    subscriptionTier: SubscriptionTier;
    alertPreferences: Array<string>;
    savedProductLists: Array<string>;
    email: string;
} {
    return {
        name: value.name,
        subscriptionTier: from_candid_SubscriptionTier_n26(_uploadFile, _downloadFile, value.subscriptionTier),
        alertPreferences: value.alertPreferences,
        savedProductLists: value.savedProductLists,
        email: value.email
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fba: null;
} | {
    easyShip: null;
} | {
    sellerFulfilled: null;
}): SellerType {
    return "fba" in value ? SellerType.fba : "easyShip" in value ? SellerType.easyShip : "sellerFulfilled" in value ? SellerType.sellerFulfilled : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pro: null;
} | {
    premium: null;
} | {
    free: null;
}): SubscriptionTier {
    return "pro" in value ? SubscriptionTier.pro : "premium" in value ? SubscriptionTier.premium : "free" in value ? SubscriptionTier.free : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: string;
} | {
    success: Array<_Product>;
}): Promise<{
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: Array<Product>;
}> {
    return "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "success" in value ? {
        __kind__: "success",
        success: await from_candid_vec_n16(_uploadFile, _downloadFile, value.success)
    } : value;
}
async function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n17(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_KeywordResearchRequest_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KeywordResearchRequest): _KeywordResearchRequest {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_OpportunityScoreFilters_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OpportunityScoreFilters): _OpportunityScoreFilters {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
async function to_candid_ProductAddRequest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductAddRequest): Promise<_ProductAddRequest> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ProductSearchFilters_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductSearchFilters): _ProductSearchFilters {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_SellerAnalysisRequest_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SellerAnalysisRequest): _SellerAnalysisRequest {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_SellerType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SellerType): _SellerType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionTier_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): _SubscriptionTier {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minScore: number;
    category?: string;
}): {
    minScore: number;
    category: [] | [string];
} {
    return {
        minScore: value.minScore,
        category: value.category ? candid_some(value.category) : candid_none()
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    subscriptionTier: SubscriptionTier;
    alertPreferences: Array<string>;
    savedProductLists: Array<string>;
    email: string;
}): {
    name: string;
    subscriptionTier: _SubscriptionTier;
    alertPreferences: Array<string>;
    savedProductLists: Array<string>;
    email: string;
} {
    return {
        name: value.name,
        subscriptionTier: to_candid_SubscriptionTier_n34(_uploadFile, _downloadFile, value.subscriptionTier),
        alertPreferences: value.alertPreferences,
        savedProductLists: value.savedProductLists,
        email: value.email
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    searchVolumeEstimate?: bigint;
    keywordDifficultyScore?: number;
    longTailSuggestions?: Array<string>;
    cpcEstimate?: number;
}): {
    searchVolumeEstimate: [] | [bigint];
    keywordDifficultyScore: [] | [number];
    longTailSuggestions: [] | [Array<string>];
    cpcEstimate: [] | [number];
} {
    return {
        searchVolumeEstimate: value.searchVolumeEstimate ? candid_some(value.searchVolumeEstimate) : candid_none(),
        keywordDifficultyScore: value.keywordDifficultyScore ? candid_some(value.keywordDifficultyScore) : candid_none(),
        longTailSuggestions: value.longTailSuggestions ? candid_some(value.longTailSuggestions) : candid_none(),
        cpcEstimate: value.cpcEstimate ? candid_some(value.cpcEstimate) : candid_none()
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    averagePrice?: number;
    averageReviews?: bigint;
    averageRating?: number;
    weaknessDetection?: Array<string>;
    listingQualityScore?: number;
}): {
    averagePrice: [] | [number];
    averageReviews: [] | [bigint];
    averageRating: [] | [number];
    weaknessDetection: [] | [Array<string>];
    listingQualityScore: [] | [number];
} {
    return {
        averagePrice: value.averagePrice ? candid_some(value.averagePrice) : candid_none(),
        averageReviews: value.averageReviews ? candid_some(value.averageReviews) : candid_none(),
        averageRating: value.averageRating ? candid_some(value.averageRating) : candid_none(),
        weaknessDetection: value.weaknessDetection ? candid_some(value.weaknessDetection) : candid_none(),
        listingQualityScore: value.listingQualityScore ? candid_some(value.listingQualityScore) : candid_none()
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lowFBACount: boolean;
    subcategory?: string;
    nonBrandedFriendly: boolean;
    ratingThreshold?: number;
    priceRange?: [number, number];
    monthlyRevenueRange?: [number, number];
    highMarginThreshold: boolean;
    bsrRange?: [bigint, bigint];
    lightweightPreference: boolean;
    category?: string;
    reviewCountMax?: bigint;
    highReviewGrowth: boolean;
}): {
    lowFBACount: boolean;
    subcategory: [] | [string];
    nonBrandedFriendly: boolean;
    ratingThreshold: [] | [number];
    priceRange: [] | [[number, number]];
    monthlyRevenueRange: [] | [[number, number]];
    highMarginThreshold: boolean;
    bsrRange: [] | [[bigint, bigint]];
    lightweightPreference: boolean;
    category: [] | [string];
    reviewCountMax: [] | [bigint];
    highReviewGrowth: boolean;
} {
    return {
        lowFBACount: value.lowFBACount,
        subcategory: value.subcategory ? candid_some(value.subcategory) : candid_none(),
        nonBrandedFriendly: value.nonBrandedFriendly,
        ratingThreshold: value.ratingThreshold ? candid_some(value.ratingThreshold) : candid_none(),
        priceRange: value.priceRange ? candid_some(value.priceRange) : candid_none(),
        monthlyRevenueRange: value.monthlyRevenueRange ? candid_some(value.monthlyRevenueRange) : candid_none(),
        highMarginThreshold: value.highMarginThreshold,
        bsrRange: value.bsrRange ? candid_some(value.bsrRange) : candid_none(),
        lightweightPreference: value.lightweightPreference,
        category: value.category ? candid_some(value.category) : candid_none(),
        reviewCountMax: value.reviewCountMax ? candid_some(value.reviewCountMax) : candid_none(),
        highReviewGrowth: value.highReviewGrowth
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bsr: bigint;
    mrp: number;
    subcategory: string;
    asin: string;
    estimatedMonthlySales: bigint;
    productName: string;
    sellerType: SellerType;
    availableStock: bigint;
    category: string;
    brand: string;
    margin: number;
    rating: number;
    price: number;
    reviewCount: bigint;
    images: Array<ExternalBlob>;
}): Promise<{
    bsr: bigint;
    mrp: number;
    subcategory: string;
    asin: string;
    estimatedMonthlySales: bigint;
    productName: string;
    sellerType: _SellerType;
    availableStock: bigint;
    category: string;
    brand: string;
    margin: number;
    rating: number;
    price: number;
    reviewCount: bigint;
    images: Array<_ExternalBlob>;
}> {
    return {
        bsr: value.bsr,
        mrp: value.mrp,
        subcategory: value.subcategory,
        asin: value.asin,
        estimatedMonthlySales: value.estimatedMonthlySales,
        productName: value.productName,
        sellerType: to_candid_SellerType_n10(_uploadFile, _downloadFile, value.sellerType),
        availableStock: value.availableStock,
        category: value.category,
        brand: value.brand,
        margin: value.margin,
        rating: value.rating,
        price: value.price,
        reviewCount: value.reviewCount,
        images: await to_candid_vec_n12(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SellerType): {
    fba: null;
} | {
    easyShip: null;
} | {
    sellerFulfilled: null;
} {
    return value == SellerType.fba ? {
        fba: null
    } : value == SellerType.easyShip ? {
        easyShip: null
    } : value == SellerType.sellerFulfilled ? {
        sellerFulfilled: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionTier): {
    pro: null;
} | {
    premium: null;
} | {
    free: null;
} {
    return value == SubscriptionTier.pro ? {
        pro: null
    } : value == SubscriptionTier.premium ? {
        premium: null
    } : value == SubscriptionTier.free ? {
        free: null
    } : value;
}
async function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
